/**
 * Calibration dataset for voice scoring engine.
 *
 * Shared by: run-calibration, validate-multi-variant, run-regression.
 * 40 examples across: messy drafts, polished, emotional, technical, short, long.
 */

export type CalibrationExample = {
  id: string;
  category:
    | "messy_draft"
    | "polished"
    | "emotional"
    | "technical"
    | "short"
    | "long";
  editorialMode: "line" | "developmental";
  original: string;
  goodEdit: string;
  badEdit: string;
};

export const CALIBRATION_DATASET: CalibrationExample[] = [
  { id: "messy-1", category: "messy_draft", editorialMode: "line", original: `So like I was thinking about this and the thing is that we need to maybe consider the fact that sometimes people dont always get what your trying to say you know? Its like when you write something and then someone reads it and they totally miss the point.`, goodEdit: `I've been thinking about this: sometimes people don't get what you're trying to say. You write something, someone reads it, and they miss the point.`, badEdit: `Upon careful reflection, it becomes evident that communicators must consider the potential for misinterpretation among their audience. Written discourse frequently fails to achieve its intended semantic transmission.` },
  { id: "messy-2", category: "messy_draft", editorialMode: "line", original: `The meeting was really really long and boring and we didnt get nothing done. Everyone was just talking in circles and going over the same stuff over and over again.`, goodEdit: `The meeting was long and boring—we didn't get anything done. Everyone kept talking in circles, going over the same stuff.`, badEdit: `The protracted assembly proved unproductive, with participants engaging in redundant discourse that failed to yield substantive outcomes.` },
  { id: "messy-3", category: "messy_draft", editorialMode: "line", original: `I think that the main problem is that we are not comunicating good enough. We need to be more clear about what we want and stuff.`, goodEdit: `I think the main problem is we're not communicating well enough. We need to be clearer about what we want.`, badEdit: `The primary impediment appears to be suboptimal interdepartmental communication protocols. Enhanced clarity regarding objectives is warranted.` },
  { id: "messy-4", category: "messy_draft", editorialMode: "developmental", original: `First we should talk about the budget. Then the timeline. Actually maybe the timeline first. The budget is important too. We need both. The team has questions.`, goodEdit: `We need to address two things: the timeline and the budget. The team has questions about both, so we should cover them together.`, badEdit: `A comprehensive review necessitates a structured approach. We shall commence with temporal considerations, subsequently transitioning to fiscal analysis. Stakeholder inquiries warrant systematic documentation.` },
  { id: "messy-5", category: "messy_draft", editorialMode: "line", original: `Their was alot of confusion about the new policy. Alot of people had questions. We should of explained it better.`, goodEdit: `There was a lot of confusion about the new policy. A lot of people had questions. We should have explained it better.`, badEdit: `Widespread ambiguity surrounded the policy implementation. Numerous inquiries emerged, suggesting inadequate preliminary communication strategies.` },
  { id: "messy-6", category: "messy_draft", editorialMode: "line", original: `So basically what happened is that the system went down and then we had to fix it and it took forever. Like hours.`, goodEdit: `What happened: the system went down, we had to fix it, and it took hours.`, badEdit: `A critical infrastructure failure necessitated extensive remediation efforts, resulting in significant operational downtime.` },
  { id: "polished-1", category: "polished", editorialMode: "line", original: `The garden had always been her refuge. When the world grew loud, she retreated to the roses and the quiet hum of bees.`, goodEdit: `The garden had always been her refuge. When the world grew loud, she retreated to the roses and the bees' quiet hum.`, badEdit: `The horticultural space consistently functioned as her sanctuary. During periods of auditory stimulation, she would withdraw to the floral arrangements and apian acoustics.` },
  { id: "polished-2", category: "polished", editorialMode: "line", original: `He spoke slowly, choosing each word with care. The room waited.`, goodEdit: `He spoke slowly, choosing each word with care. The room waited.`, badEdit: `He articulated his thoughts with deliberate precision, meticulously selecting his lexicon. The assembled attendees maintained anticipatory silence.` },
  { id: "polished-3", category: "polished", editorialMode: "developmental", original: `The argument builds from a simple premise: we underestimate the cost of inaction. The middle section explores three case studies. The conclusion ties them together.`, goodEdit: `The argument builds from a simple premise—we underestimate the cost of inaction. Three case studies in the middle explore this. The conclusion ties them together.`, badEdit: `Commencing with a foundational thesis regarding the undervaluation of passive strategies, the discourse subsequently examines empirical instances before synthesizing findings in the denouement.` },
  { id: "polished-4", category: "polished", editorialMode: "line", original: `She didn't believe in luck. She believed in preparation meeting opportunity.`, goodEdit: `She didn't believe in luck. She believed in preparation meeting opportunity.`, badEdit: `She rejected stochastic interpretations of success, instead subscribing to a paradigm wherein meticulous preparation intersects with fortuitous circumstances.` },
  { id: "polished-5", category: "polished", editorialMode: "line", original: `The old house had character. Creaking floors, uneven doorframes, windows that didn't quite close. She loved it anyway.`, goodEdit: `The old house had character: creaking floors, uneven doorframes, windows that didn't quite close. She loved it anyway.`, badEdit: `The domicile exhibited distinctive architectural attributes, including acoustic floorboards, asymmetrical apertures, and suboptimal fenestration. Notwithstanding these deficiencies, she maintained affection for the property.` },
  { id: "polished-6", category: "polished", editorialMode: "line", original: `We tried. We failed. We learned.`, goodEdit: `We tried, we failed, we learned.`, badEdit: `A sequence of attempts culminated in unsuccessful outcomes, from which valuable pedagogical insights were derived.` },
  { id: "emotional-1", category: "emotional", editorialMode: "line", original: `I miss him so much it hurts. Every morning I wake up and for a second I forget, and then it hits me again.`, goodEdit: `I miss him so much it hurts. Every morning I wake up, forget for a second, then it hits me again.`, badEdit: `The emotional void engendered by his absence manifests as somatic distress. Diurnal consciousness is punctuated by brief amnesia followed by renewed affective recognition.` },
  { id: "emotional-2", category: "emotional", editorialMode: "line", original: `I can't believe she's gone. Just like that. No warning. No goodbye.`, goodEdit: `I can't believe she's gone. Just like that—no warning, no goodbye.`, badEdit: `The suddenness of her departure defies cognitive integration. The absence of premonitory indicators or valedictory exchange compounds the disorientation.` },
  { id: "emotional-3", category: "emotional", editorialMode: "line", original: `We were so excited! This was it! Everything we'd worked for! And then they said no.`, goodEdit: `We were so excited. This was it—everything we'd worked for. And then they said no.`, badEdit: `Initial enthusiasm was considerable, as the culmination of our efforts appeared imminent. Subsequently, our proposal received a negative determination.` },
  { id: "emotional-4", category: "emotional", editorialMode: "developmental", original: `The diagnosis changed everything. First came the shock. Then the fear. Then, slowly, a kind of resolve. We would get through this.`, goodEdit: `The diagnosis changed everything. Shock first, then fear, then slowly a kind of resolve. We would get through this.`, badEdit: `The medical assessment precipitated a comprehensive reorientation. Sequential affective states included disbelief, trepidation, and eventual determination. Collective resilience was affirmed.` },
  { id: "emotional-5", category: "emotional", editorialMode: "line", original: `I'm so proud of you. Really. You have no idea how much this means to me.`, goodEdit: `I'm so proud of you. Really. You have no idea how much this means to me.`, badEdit: `Your achievements have elicited considerable approbation. The significance of this milestone cannot be overstated from my perspective.` },
  { id: "emotional-6", category: "emotional", editorialMode: "line", original: `Why didn't you tell me? I would have understood. I would have helped.`, goodEdit: `Why didn't you tell me? I would've understood. I would've helped.`, badEdit: `The omission of this information precluded my capacity to provide assistance. Full disclosure would have enabled a more supportive response.` },
  { id: "technical-1", category: "technical", editorialMode: "line", original: `The API returns a 200 status code when the request succeeds. Error responses use 4xx codes.`, goodEdit: `The API returns 200 when the request succeeds. Error responses use 4xx codes.`, badEdit: `Successful requests elicit HTTP 200 responses from the API. Erroneous scenarios are communicated via client-error status codes in the 4xx range.` },
  { id: "technical-2", category: "technical", editorialMode: "line", original: `To deploy, run the build script first. Then push to the staging environment. Verify the health checks before promoting to prod.`, goodEdit: `To deploy: run the build script first, then push to staging. Verify health checks before promoting to prod.`, badEdit: `Deployment necessitates sequential execution of the build artifact generation, followed by transmission to the staging infrastructure. Pre-production promotion requires validation of wellness endpoints.` },
  { id: "technical-3", category: "technical", editorialMode: "developmental", original: `The cache invalidation is broken. Users see stale data. We need to fix the TTL logic. Also the fallback when the cache misses.`, goodEdit: `The cache invalidation is broken—users see stale data. We need to fix two things: the TTL logic and the fallback when the cache misses.`, badEdit: `Cache invalidation mechanisms exhibit dysfunctional behavior, resulting in stale data propagation. Remediation requires addressing both temporal-to-live configuration and cache-miss fallback strategies.` },
  { id: "technical-4", category: "technical", editorialMode: "line", original: `The migration will take approximately 2 hours. Downtime is expected during the cutover.`, goodEdit: `The migration will take ~2 hours. Expect downtime during cutover.`, badEdit: `The data transfer operation is projected to consume approximately 120 minutes. Service interruption is anticipated during the transition phase.` },
  { id: "technical-5", category: "technical", editorialMode: "line", original: `We use connection pooling to reduce latency. Each worker maintains a pool of 10 connections.`, goodEdit: `We use connection pooling to reduce latency. Each worker maintains a pool of 10 connections.`, badEdit: `Connection pooling is employed to mitigate latency. Worker processes are configured with decadal connection allocations.` },
  { id: "technical-6", category: "technical", editorialMode: "line", original: `The bug occurs when the user submits the form before the validation completes. Race condition.`, goodEdit: `The bug occurs when the user submits before validation completes—a race condition.`, badEdit: `The defect manifests under conditions wherein form submission precedes validation completion, constituting a temporal synchronization anomaly.` },
  { id: "short-1", category: "short", editorialMode: "line", original: `Call me tomorrow. We need to talk.`, goodEdit: `Call me tomorrow—we need to talk.`, badEdit: `Please initiate telephonic communication at your earliest convenience. A substantive discussion is warranted.` },
  { id: "short-2", category: "short", editorialMode: "line", original: `The coffee was cold. The meeting was worse.`, goodEdit: `The coffee was cold; the meeting was worse.`, badEdit: `The beverage had achieved thermal equilibrium with ambient conditions. The subsequent assembly proved even less satisfactory.` },
  { id: "short-3", category: "short", editorialMode: "line", original: `I agree. Let's do it.`, goodEdit: `I agree. Let's do it.`, badEdit: `I am in concurrence with the proposed course of action. We shall proceed accordingly.` },
  { id: "short-4", category: "short", editorialMode: "line", original: `She left at dawn. No note. No explanation.`, goodEdit: `She left at dawn—no note, no explanation.`, badEdit: `Her departure occurred during the crepuscular period. No written communication or rationale was provided.` },
  { id: "short-5", category: "short", editorialMode: "line", original: `The deadline is Friday. No extensions.`, goodEdit: `The deadline is Friday. No extensions.`, badEdit: `Submission is required by the conclusion of the workweek. Deferral requests will not be accommodated.` },
  { id: "short-6", category: "short", editorialMode: "line", original: `It worked. I can't believe it actually worked.`, goodEdit: `It worked. I can't believe it actually worked.`, badEdit: `The methodology yielded successful outcomes. The positive result exceeded anticipatory parameters.` },
  { id: "long-1", category: "long", editorialMode: "developmental", original: `The project started with good intentions. We wanted to build something that would help people. The team was small but dedicated. We had a clear vision. Or so we thought. As the months went on, scope creep set in. Every stakeholder had a new feature request. We said yes to too many things. The timeline stretched. The budget stretched. Morale dipped. Some people left. We shipped something eventually. It wasn't what we'd imagined. But it was something.`, goodEdit: `The project started with good intentions—we wanted to build something that would help people. The team was small but dedicated, and we had a clear vision. Or so we thought. As months passed, scope creep set in. Every stakeholder had a new feature request, and we said yes to too many. The timeline stretched, the budget stretched, morale dipped. Some people left. We shipped something eventually. It wasn't what we'd imagined, but it was something.`, badEdit: `Commencing with altruistic objectives, the initiative aimed to develop a solution benefiting end users. The compact yet committed team possessed an ostensibly coherent strategic direction. However, temporal progression revealed progressive scope expansion. Stakeholder demands proliferated, and acquiescence was excessive. Temporal and fiscal parameters were compromised. Organizational morale declined. Personnel attrition occurred. A deliverable was ultimately released, albeit divergent from initial conceptualization.` },
  { id: "long-2", category: "long", editorialMode: "line", original: `I've been thinking about what you said. About the way we communicate. You're right that we could do better. I tend to shut down when things get hard. I don't mean to. It's just easier than facing the discomfort. But that's not fair to you. You deserve someone who stays in the conversation. I'm going to try. That's all I can promise right now. I'm going to try.`, goodEdit: `I've been thinking about what you said—about the way we communicate. You're right that we could do better. I tend to shut down when things get hard; I don't mean to, it's just easier than facing the discomfort. But that's not fair to you. You deserve someone who stays in the conversation. I'm going to try. That's all I can promise right now.`, badEdit: `Reflection upon your communicative observations has occurred. Your assessment regarding improvement potential is valid. I exhibit withdrawal tendencies during challenging interactions, unintentionally. Avoidance predominates over discomfort engagement. This constitutes inequitable treatment. You merit a conversational partner who maintains engagement. Effort will be exerted. Presently, that constitutes the extent of my commitment.` },
  { id: "long-3", category: "long", editorialMode: "developmental", original: `The report covers three areas. First we look at revenue. Revenue was up 12% year over year. The main driver was the new product line. Second we look at costs. Costs were flat. That's good. Third we look at headcount. We added 15 people. Mostly in engineering. The outlook for next quarter is positive. We expect similar growth.`, goodEdit: `The report covers three areas. Revenue was up 12% year over year, driven mainly by the new product line. Costs were flat—good. Headcount grew by 15, mostly in engineering. The outlook for next quarter is positive; we expect similar growth.`, badEdit: `The document addresses three domains. Revenue analysis indicates 12% YoY increase, attributable primarily to product line expansion. Cost structures remained stable. Personnel augmentation of 15 FTE occurred, predominantly within engineering functions. Forward projections suggest continued positive trajectory.` },
  { id: "long-4", category: "long", editorialMode: "line", original: `The restaurant was packed. We had to wait forty minutes for a table. The host was apologetic. The food, when it finally came, was worth it. The pasta was perfect. The wine was good. The noise level was high but we didn't mind. We were celebrating. It had been a long year.`, goodEdit: `The restaurant was packed—we waited forty minutes for a table. The host was apologetic. The food, when it finally came, was worth it: perfect pasta, good wine. The noise level was high but we didn't mind. We were celebrating. It had been a long year.`, badEdit: `The establishment exhibited high occupancy. Table acquisition required a 40-minute interval. The host expressed regret. The culinary offerings, upon arrival, justified the delay. The pasta achieved optimal preparation. The wine was satisfactory. Acoustic conditions were elevated but acceptable. The occasion warranted celebration following an arduous annum.` },
  { id: "long-5", category: "long", editorialMode: "line", original: `She walked into the room and everyone stopped talking. Not because she was loud. She wasn't. It was something about the way she carried herself. Confidence without arrogance. She smiled at a few people. She found a seat. The meeting began.`, goodEdit: `She walked into the room and everyone stopped talking. Not because she was loud—she wasn't. It was something about the way she carried herself: confidence without arrogance. She smiled at a few people, found a seat. The meeting began.`, badEdit: `Her entrance precipitated conversational cessation. The effect was not attributable to auditory volume. Her bearing conveyed assurance absent hubris. She acknowledged several attendees. She located seating. Proceedings commenced.` },
  { id: "long-6", category: "long", editorialMode: "developmental", original: `We need to decide on the approach. Option A is faster but riskier. Option B takes longer but is more thorough. Option C is a hybrid. I'm leaning toward B. The extra time seems worth it. What do you think?`, goodEdit: `We need to decide on the approach. Option A is faster but riskier; Option B takes longer but is more thorough; Option C is a hybrid. I'm leaning toward B—the extra time seems worth it. What do you think?`, badEdit: `A methodological determination is required. Alternative A offers expedience at elevated risk. Alternative B necessitates extended duration but provides comprehensive coverage. Alternative C represents a synthesis. My inclination favors B. The temporal investment appears justified. Your perspective is solicited.` },
  { id: "mixed-1", category: "messy_draft", editorialMode: "line", original: `Its important to note that the data shows a clear trend. We can see that over time things have gotten better. Alot better actually.`, goodEdit: `It's important to note the data shows a clear trend. Over time, things have gotten better—a lot better, actually.`, badEdit: `Empirical evidence indicates a statistically significant positive trajectory. Longitudinal analysis reveals substantial improvement across measured dimensions.` },
  { id: "mixed-2", category: "emotional", editorialMode: "line", original: `I dont know what to say. I'm just so grateful. For everything. For you.`, goodEdit: `I don't know what to say. I'm just so grateful—for everything, for you.`, badEdit: `Verbal expression proves inadequate. Profound appreciation is felt. Comprehensive gratitude is extended.` },
  { id: "mixed-3", category: "technical", editorialMode: "line", original: `The fix is in the latest release. You need to update. The old version has a security vulnerability.`, goodEdit: `The fix is in the latest release. You need to update—the old version has a security vulnerability.`, badEdit: `Remediation has been incorporated into the most recent distribution. Upgrade is mandatory. Preceding iterations contain exploitable deficiencies.` },
  { id: "mixed-4", category: "polished", editorialMode: "line", original: `The light changed. She didn't move. The cars honked. She still didn't move.`, goodEdit: `The light changed. She didn't move. Cars honked. She still didn't move.`, badEdit: `The traffic signal transitioned. She remained stationary. Auditory stimuli from vehicular sources ensued. Immobility persisted.` },
  { id: "mixed-5", category: "long", editorialMode: "line", original: `We learned three things from the pilot. First, users want simpler onboarding. Second, the dashboard is confusing. Third, support requests spike on Mondays. We're addressing all three in the next sprint.`, goodEdit: `We learned three things from the pilot: users want simpler onboarding, the dashboard is confusing, and support requests spike on Mondays. We're addressing all three in the next sprint.`, badEdit: `The pilot yielded three insights. User preference favors streamlined onboarding. Dashboard UX exhibits confusion. Support volume demonstrates Monday concentration. Remediation is scheduled for the subsequent iteration.` },
];
